blueprint:
  name: Cover Control with Two Buttons
  description: >
    Control a cover with two buttons: one for opening and one for closing.
    Buttons will stop the cover if it's moving.
  domain: automation
  input:
    cover_entity:
      name: Cover
      description: The cover entity to control.
      selector:
        entity:
          domain: cover
    up_button:
      name: Up Button
      description: The button to open the cover.
      selector:
        device:
          integration: mqtt
    up_button_trigger:
      name: Up Button Trigger
      description: Trigger for the up button.
      default: action_arrow_left_click
      selector:
        text:
          multiline: false
    down_button:
      name: Down Button
      description: The button to close the cover.
      selector:
        device:
          integration: mqtt
    down_button_trigger:
      name: Down Button Trigger
      description: Trigger for the down button.
      default: action_arrow_right_click
      selector:
        text:
          multiline: false

trigger:
  - platform: device
    device_id: !input up_button
    domain: mqtt
    type: action
    subtype: !input up_button_trigger
    id: up_button_trigger

  - platform: device
    device_id: !input down_button
    domain: mqtt
    type: action
    subtype: !input down_button_trigger
    id: down_button_trigger

condition: []

action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: device
                domain: cover
                entity_id: !input cover_entity
                type: is_closing
              - condition: device
                domain: cover
                entity_id: !input cover_entity
                type: is_opening
        sequence:
          - service: cover.stop_cover
            target:
              entity_id: !input cover_entity

      - conditions:
          - condition: not
            conditions:
              - condition: device
                domain: cover
                entity_id: !input cover_entity
                type: is_closing
              - condition: device
                domain: cover
                entity_id: !input cover_entity
                type: is_opening
        sequence:
          - choose:
              - conditions:
                  - condition: trigger
                    id: up_button_trigger
                sequence:
                  - service: cover.open_cover
                    target:
                      entity_id: !input cover_entity

              - conditions:
                  - condition: trigger
                    id: down_button_trigger
                sequence:
                  - service: cover.close_cover
                    target:
                      entity_id: !input cover_entity

mode: single
